
#include <Lib\Hcv\PixelTypes.cpp>
#include <Lib\Hcv\funcs1.cpp>
#include <Lib\Hcv\ConvKernel.cpp>
#include <Lib\Hcv\Hsv.cpp>
#include <Lib\Hcv\HistoGram.cpp>
#include <Lib\Hcv\InitLib.cpp>
#include <Lib\Hcv\RegionSegmentor.cpp>
#include <Lib\Hcv\RegionSegmentor2.cpp>
#include <Lib\Hcv\RegionSegmentor3.cpp>
#include <Lib\Hcv\RegionSegmentor4.cpp>
#include <Lib\Hcv\RegionSegmentor5.cpp>
#include <Lib\Hcv\RegionSegmentor6.cpp>
#include <Lib\Hcv\RegionSegmentor7.cpp>
#include <Lib\Hcv\RegionSegmentor8.cpp>
#include <Lib\Hcv\RegionSegmentor9.cpp>
#include <Lib\Hcv\RegionSegmentor10.cpp>
#include <Lib\Hcv\RegionSegmentor11.cpp>
#include <Lib\Hcv\RegionSegmentor12.cpp>
#include <Lib\Hcv\RegionSegmentor13.cpp>
#include <Lib\Hcv\RegionSegmentor14.cpp>
#include <Lib\Hcv\RegionSegmentor15.cpp>
#include <Lib\Hcv\RegionSegmentor16.cpp>
#include <Lib\Hcv\RegionSegmentor17.cpp>
#include <Lib\Hcv\RegionSegmentor18.cpp>
#include <Lib\Hcv\RegionSegmentor19.cpp>
#include <Lib\Hcv\RegionSegmentor20.cpp>
#include <Lib\Hcv\RegionSegmentor21.cpp>
#include <Lib\Hcv\RegionSegmentor22.cpp>
#include <Lib\Hcv\RegionSegmentor23.cpp>
#include <Lib\Hcv\RegionSegmentor24.cpp>
#include <Lib\Hcv\RegionSegmentor25.cpp>
#include <Lib\Hcv\RegionSegmentor26.cpp>
#include <Lib\Hcv\RegionSegmentor27.cpp>
#include <Lib\Hcv\RegionSegmentor28.cpp>
#include <Lib\Hcv\RegionSegmentor29.cpp>
#include <Lib\Hcv\RegionSegmentor30.cpp>
#include <Lib\Hcv\RegionSegmentor31.cpp>
#include <Lib\Hcv\RegionSegmentor32.cpp>
#include <Lib\Hcv\RegionSegmentor33.cpp>
#include <Lib\Hcv\RegionSegmentor34.cpp>
#include <Lib\Hcv\RegionSegmentor35.cpp>
#include <Lib\Hcv\RegionSegmentor36.cpp>
#include <Lib\Hcv\RegionSegmentor37.cpp>
#include <Lib\Hcv\RegionSegmentor38.cpp>
#include <Lib\Hcv\RegionSegmentor39.cpp>
#include <Lib\Hcv\RegionSegmentor40.cpp>
#include <Lib\Hcv\RegionSegmentor41.cpp>
#include <Lib\Hcv\RegionSegmentor42.cpp>
#include <Lib\Hcv\RegionSegmentor43.cpp>
#include <Lib\Hcv\AdaptiveConv.cpp>
#include <Lib\Hcv\AdaptiveConv2.cpp>
#include <Lib\Hcv\CusteringTries.cpp>
#include <Lib\Hcv\ClusteringMgr.cpp>
#include <Lib\Hcv\ImageClusteringMgr.cpp>
#include <Lib\Hcv\SignalOneDim.cpp>
#include <Lib\Hcv\SobelBuilder.cpp>
#include <Lib\Hcv\PNEdgeBuilder.cpp>
#include <Lib\Hcv\IOMgr.cpp>
#include <Lib\Hcv\LinePath.cpp>
#include <Lib\Hcv\LinePathInt.cpp>
#include <Lib\Hcv\Signal1D.cpp>
#include <Lib\Hcv\Signal1DViewer.cpp>
#include <Lib\Hcv\Filter1D.cpp>
#include <Lib\Hcv\ConvFilter1D.cpp>
//#include <Lib\Hcv\LinearColorFilter1D.cpp>
#include <Lib\Hcv\LinearAvgFilter1D.cpp>
#include <Lib\Hcv\LinearDiffFilter1D.cpp>
#include <Lib\Hcv\ImageLineViewer.cpp>
#include <Lib\Hcv\ColorFilter1D.cpp>
#include <Lib\Hcv\CompositeColorFilter1D.cpp>
#include <Lib\Hcv\ColorFilter1DSystem.cpp>
#include <Lib\Hcv\AbsFilter1D.cpp>
#include <Lib\Hcv\ScaleFixFilter1D.cpp>
#include <Lib\Hcv\PeakCleanerFilter1D.cpp>
#include <Lib\Hcv\PeakMarkerFilter1D.cpp>
#include <Lib\Hcv\ValleyMaximizerFilter1D.cpp>
#include <Lib\Hcv\ImageLineViewer2.cpp>
#include <Lib\Hcv\ImageLineViewer3.cpp>
#include <Lib\Hcv\SerialColorMgr.cpp>
#include <Lib\Hcv\ConflictScanner.cpp>
#include <Lib\Hcv\ConflictScanner2.cpp>
#include <Lib\Hcv\FiltSysDebug.cpp>
#include <Lib\Hcv\ValleyMarkerFilter1D.cpp>
#include <Lib\Hcv\DiagonalLinePath.cpp>
#include <Lib\Hcv\NegDiagonalLinePath.cpp>
#include <Lib\Hcv\MaxFilter1D.cpp>
#include <Lib\Hcv\BadRootScanner.cpp>
#include <Lib\Hcv\CircleContPath.cpp>
#include <Lib\Hcv\CircleContourOfPix.cpp>
#include <Lib\Hcv\CircleContourOfPix2.cpp>
#include <Lib\Hcv\CircleContourOfPix3.cpp>
#include <Lib\Hcv\CircleContourOfPix4.cpp>
#include <Lib\Hcv\CircleContourOfPix5.cpp>
#include <Lib\Hcv\MultiColorSignal1DViewer.cpp>
#include <Lib\Hcv\CircDiff.cpp>
#include <Lib\Hcv\CircDiff2.cpp>
#include <Lib\Hcv\SlideMgr.cpp>
#include <Lib\Hcv\LineStepper.cpp>
#include <Lib\Hcv\LineStepperByAngle.cpp>
#include <Lib\Hcv\ScanDirMgr.cpp>
#include <Lib\Hcv\ImgDataMgr_Simple.cpp>
#include <Lib\Hcv\ImgDataMgr_Simple_2.cpp>
#include <Lib\Hcv\IImgDataMgr.cpp>
#include <Lib\Hcv\ImgDataElm_Simple.cpp>
#include <Lib\Hcv\ScanDirMgrColl.cpp>
#include <Lib\Hcv\SubGradMgr.cpp>
#include <Lib\Hcv\ImgGradMgr.cpp>
#include <Lib\Hcv\ImgGradMgr_2.cpp>
#include <Lib\Hcv\ImgAvgingMgr.cpp>
#include <Lib\Hcv\Avging_ScanDirMgrExt.cpp>
#include <Lib\Hcv\DeltaSignal.cpp>
#include <Lib\Hcv\SingFilt1D2.cpp>
#include <Lib\Hcv\Filt1D2DataMgr.cpp>
#include <Lib\Hcv\AvgFilt1D2.cpp>
#include <Lib\Hcv\Filt1D2System.cpp>
#include <Lib\Hcv\Filt1D2SysProto.cpp>
#include <Lib\Hcv\ScanTryMgr.cpp>
#include <Lib\Hcv\DifFilt1D2.cpp>
#include <Lib\Hcv\PeakMarkerFilt1D2.cpp>
#include <Lib\Hcv\AbsFilt1D2.cpp>
#include <Lib\Hcv\ZeroCrossingFilt1D2.cpp>
#include <Lib\Hcv\MaxFilt1D2.cpp>
#include <Lib\Hcv\EdgeScanMgr.cpp>
#include <Lib\Hcv\EdgeScan.cpp>
#include <Lib\Hcv\ScanTryMgr2.cpp>
#include <Lib\Hcv\ScanTryMgr_3.cpp>
#include <Lib\Hcv\ScanTryMgr_4.cpp>
#include <Lib\Hcv\ScanTryDbg.cpp>
#include <Lib\Hcv\ZeroCrossing_2_Filt1D2.cpp>
#include <Lib\Hcv\Ptr_Filt1D2DataMgr.cpp>
#include <Lib\Hcv\ImageWatershedMgr.cpp>
#include <Lib\Hcv\IImgPopulation.cpp>
#include <Lib\Hcv\ImgPopulation_Simple.cpp>











